days = ['maandag','dinsdag','woensdag','donderdag','vrijdag','zaterdag','zondag']
print('')
print('')
print('dit zijn de dagen in een week')
print(*days[0:7])
print('')
print('')
print('dit zijn alle werkdagen')
print(*days[0:5])
print('')
print('')
print('dit is het weekend')
print(*days[5:7])
print('')
print('')
print('hier is he lijstje achterstevoren')
days.reverse()
print(*days[0:7])

